# specialai:villages.toml
# This config contains various options to control village tweaks, villager behavior, and reputation.

  # Block List fields: General format = [ "namespace:block_name[property1=value1,...]", ... ]
  #   Block lists are arrays of blocks and partial block states.
  #   Blocks are defined by their key in the block registry, usually following the pattern 'namespace:block_name'.
  #   An asterisk '*' can be used to match all blocks belonging to X namespace. For example, 'minecraft:*' will match
  #     all vanilla blocks.
  #   Block tags can also be used here. To declare a tag, start with a '#' followed by the rest of the tag path.
  #   Tag example: '#minecraft:beehive_inhabitors'
  #   List entries by default match any block state. The block states to match can be narrowed down by specifying
  #     properties. The syntax for block state properties is the same as for commands. Any properties not specified will
  #     match any value. For example, 'minecraft:beehive[honey_level=5]' will match any full beehives, regardless of the
  #     direction they face.
  #   Note that tags and namespace entries are not block state sensitive; they only care about the base block
  #       Priority order: specific entries > tag entries > namespace entries

  # Registry entry-value list fields: General format = [ "namespace:registry_name value1 value2 ...", ... ]
  #   Registry entry-value lists are arrays of registry keys. Many things in the game, such as blocks or potions, are
  #     defined by their registry key within a registry. For example, all items are registered in the "minecraft:item"
  #     registry.
  #   Registry entry-value lists may have one or multiple numeric values linked to each entry.
  #   'default' can be used instead of a registry key to provide default values.
  #   An asterisk '*' can be used to match all registry entries/keys belonging to X namespace. For example,
  #     'minecraft:*' will match all vanilla entries.
  #   Tags can also be used here. To declare a tag, start with a '#' followed by the rest of the tag path.
  #   Tag example: '#minecraft:oak_logs'
  #       Priority order: specific entries > tag entries > namespace entries > default

  # Entity List fields: General format = [ "namespace:entity_type value1 value2 ...", ... ]
  #   Entity lists are arrays of entity types. Some entity lists specify a number of values linked to each entity type.
  #   Entity types are defined by their key in the entity registry, usually following the pattern
  #     'namespace:entity_name'.
  #   'default' can be used instead of an entity type registry key to provide default values for all entities.
  #   List entries by default match any entity type derived from (i.e. based on) their entity type. For example,
  #     '~minecraft:zombie'.
  #     There is no steadfast rule about extending, even in vanilla, but the hope is that mod-added mobs will extend
  #       their base mob.
  #   An asterisk '*' can be used to match all registry entries belonging to X namespace. For example, 'minecraft:*'
  #     will match all vanilla entries.
  #   Entity type tags can also be used here. To declare a tag, start with a '#' followed by the rest of the tag path.
  #   Tag example: '#minecraft:beehive_inhabitors'
  #       Priority order: specific entries > tag entries > namespace entries > default



# Category: behavior_tweaks
# Options for misc. AI tweaks to villagers.

  # If the player's reputation with a villager is equal to or lower than this value, the villager will refuse to trade.
  # <Integer> Range: Any Value, Default: -100
  behavior_tweaks.refuse_trade_rep = -100


# Category: reputation
# Options for reputation gain and reputation loss.

  # A list of blocks that may either anger or please nearby villagers inside villages when destroyed by a player.
  # The numeric value in each entry determines the reputation change.
  # Negative values mean bad reputation, positive means good reputation.
  # Note that breaking blocks will only affect 'minor negative' or 'minor positive' reputation, which both have an
  #   upper limit of 200.
  # <Registry Entry-value List> Format: [ "namespace:registry_name value1 value2 ...", ... ], Default: [
  #   "minecraft:hay_block -2.0", "minecraft:chest -5.0", "minecraft:furnace -4.0", "minecraft:barrel -4.0",
  #   "minecraft:tall_grass 0.0", "minecraft:grass 0.0", "minecraft:fern 0.0", "#minecraft:doors -3.0",
  #   "#minecraft:flowers 0.0", "default -1.0" ]
  #    Target registry: ResourceKey[minecraft:root / minecraft:block]
  #    Range for Values: Any Value
  reputation.reputation_changing_blocks = [
    "minecraft:hay_block -2.0",
    "minecraft:chest -5.0",
    "minecraft:furnace -4.0",
    "minecraft:barrel -4.0",
    "minecraft:tall_grass 0.0",
    "minecraft:grass 0.0",
    "minecraft:fern 0.0",
    "#minecraft:doors -3.0",
    "#minecraft:flowers 0.0",
    "default -1.0"
  ]
  # If a player's reputation is greater than or equal to this value with a villager, the observing villager will not
  #   be bothered if the player breaks a block in the village that would otherwise give bad reputation.
  # <Integer> Range: Any Value, Default: 100
  reputation.break_block_threshold = 100

  # A list of entities that may either anger or please nearby villagers inside villages when killed by a player.
  # The numeric value in each entry determines the reputation change.
  # Negative values mean bad reputation, positive means good reputation.
  # Killing villagers already gives major bad reputation in vanilla, and cannot be overridden here.
  # Note that killing creatures will only affect 'minor negative' or 'minor positive' reputation, which both have an
  #   upper limit of 200.
  # <Entity List> Format: [ "namespace:entity_type value1 value2 ...", ... ], Default: [ "minecraft:cat -20.0",
  #   "minecraft:cow -5.0", "minecraft:sheep -5.0", "minecraft:pig -5.0", "minecraft:chicken -3.0", "minecraft:horse -
  #   15.0", "minecraft:iron_golem -40.0", "minecraft:wandering_trader -40.0", "minecraft:zombie 4.0", ... ]
  #    Range for Values: Any Value
  reputation.reputation_changing_creatures = [
    "minecraft:cat -20.0",
    "minecraft:cow -5.0",
    "minecraft:sheep -5.0",
    "minecraft:pig -5.0",
    "minecraft:chicken -3.0",
    "minecraft:horse -15.0",
    "minecraft:iron_golem -40.0",
    "minecraft:wandering_trader -40.0",
    "minecraft:zombie 4.0",
    "minecraft:skeleton 3.0",
    "minecraft:creeper 5.0",
    "minecraft:enderman 2.0",
    "minecraft:spider 2.0",
    "minecraft:slime 1.0",
    "minecraft:vex 1.0",
    "#minecraft:raiders 15.0"
  ]
  # If a player's reputation is greater than or equal to this value with a villager, the observing villager will not
  #   be bothered if the player kills a creature in the village that would otherwise give bad reputation.
  # <Integer> Range: Any Value, Default: 190
  reputation.kill_creature_threshold = 190

  # If greater than 0, players will anger nearby farmer villagers if they trample farmland, losing the specified
  #   amount of reputation.
  # Note that farmer villagers take trampling personally, and will be displeased even if it happens outside a village.
  # <Integer> Range: -200 ~ 0, Default: -4
  reputation.trample_farmland_anger = -4


# Category: villager_names
# Name and job title components for randomly generated villager names.

  # If false, none of the below options will do anything and SpecialAI will not generate random names for villagers.
  # <Boolean> Valid Values: { true, false }, Default: true
  villager_names.master_toggle = true

  # A list of name components to pick from when generating a random name for a villager.
  # <String List> Format: [ "string1", "string2", ... ], Default: [ "grab", "thar", "ger", "ald", "mas", "on", "o",
  #   "din", "thor", "jon", "ath", "an", "burb", "en", "a", "e", "i", "u", "hab", "bloo", "ena", "dit", "aph", "ern",
  #   "bor", "dav", "id", "toast", "son", "dottir", "for", "wen", "lob", "ed", "die", "van", "y", "zap", "ear", "ben",
  #   "don", "bran", "gro", "jen", "bob", "ette", "ere", "man", "qua", "bro", "cree", "per", "skel", "ton", "zom",
  #   "bie", "wolf", "end", "er", "pig", "sil", "ver", "fish", "cow", "chic", "ken", "sheep", "lla", "rab", "bit",
  #   "squid", "hell", "scrub", "loaf", "bonk", "clonk", "bink", "guy", "gal", "wool", "flo", "fee", "fi", "fo", "fum",
  #   "green", "blue", "red", "seed", "wheat", "boat", "rod", "poke", "bow" ]
  villager_names.base_name_components = [
    "grab",
    "thar",
    "ger",
    "ald",
    "mas",
    "on",
    "o",
    "din",
    "thor",
    "jon",
    "ath",
    "an",
    "burb",
    "en",
    "a",
    "e",
    "i",
    "u",
    "hab",
    "bloo",
    "ena",
    "dit",
    "aph",
    "ern",
    "bor",
    "dav",
    "id",
    "toast",
    "son",
    "dottir",
    "for",
    "wen",
    "lob",
    "ed",
    "die",
    "van",
    "y",
    "zap",
    "ear",
    "ben",
    "don",
    "bran",
    "gro",
    "jen",
    "bob",
    "ette",
    "ere",
    "man",
    "qua",
    "bro",
    "cree",
    "per",
    "skel",
    "ton",
    "zom",
    "bie",
    "wolf",
    "end",
    "er",
    "pig",
    "sil",
    "ver",
    "fish",
    "cow",
    "chic",
    "ken",
    "sheep",
    "lla",
    "rab",
    "bit",
    "squid",
    "hell",
    "scrub",
    "loaf",
    "bonk",
    "clonk",
    "bink",
    "guy",
    "gal",
    "wool",
    "flo",
    "fee",
    "fi",
    "fo",
    "fum",
    "green",
    "blue",
    "red",
    "seed",
    "wheat",
    "boat",
    "rod",
    "poke",
    "bow"
  ]
  # A list of rolls to determine how many name components can be picked when generating a villager name.
  # For example, if the list contains 5 numbers, a villager name may generate with 1-5 total components.
  # The value of each number determines the chance to add a component, so 1 would equal a 1/1 chance, and 64 would
  #   equal a 1/64 chance.
  # <Integer List> Format: [ "integer1", "integer2", ... ], Default: [ "1", "1", "4", "16", "64" ]
  villager_names.component_rolls = [
    "1",
    "1",
    "4",
    "16",
    "64"
  ]

  # A list of prefixes that may be added to a villager's first name.
  # <String List> Format: [ "string1", "string2", ... ], Default: [ "Mc", "Mac" ]
  villager_names.name_prefixes = [
    "Mc",
    "Mac"
  ]
  # The chance for a prefix from the above list to be added to the name of a villager.
  # <Number> Range: 0.0 ~ 1.0, Default: 0.01
  villager_names.name_prefix_chance = 0.01

  # A list of villager professions and all job titles associated with them.
  # Existing titles can be modified here, and new ones can be added for professions from other mods.
  # When a villager picks up a new profession, a random job title for that profession is picked from this list.
  # Adding the same title multiple times essentially just gets it picked more commonly.
  # <Profession and Components List> Format: [ "profession_and_components1", "profession_and_components2", ... ],
  #   Default: [ "minecraft:cleric Cleric Cleric Cleric Priest Priest Priest Father Mother Preacher Reverend Rabbi
  #   Chaplain Minister Churchman Healer Storyteller Mystic Enchanter Diviner Oracle Augur Prophet Seer Holyman Sage
  #   Wiseman Elder", "minecraft:butcher Butcher Butcher Meatman Meatman Meatmonger Meatmonger Meatvendor Cowslayer
  #   Sheepslayer Chickenslayer Rabbitslayer", "minecraft:librarian Librarian Librarian Curator Curator Bookbinder
  #   Bookbinder Bookvendor Bookvendor Cataloger Researcher Bookman Bibliothecary Recordkeeper Bookmonger",
  #   "minecraft:nitwit Nitwit Blockhead Fool Dimwit Dork Dunce Jerk Moron Pinhead Ninny Simpleton Philosopher
  #   Daydreamer Roamer Nincompoop", "minecraft:fisherman Fisherman Fisherman Fisher Fisher Angler Angler Fishmonger
  #   Fishmonger Piscator Rodman Troller Trawler Fishman Skipper Captain Fishvendor", "minecraft:weaponsmith Weaponsmith
  #   Weaponsmith Swordsmith Swordsmith Weaponmonger Weaponmonger Weaponcrafter Weaponmaker Weaponmaster Weaponman
  #   Swordcrafter Swordmaker Swordmaster Weaponvendor Swordmonger Swordvendor", "minecraft:cartographer Cartographer
  #   Cartographer Mapmaker Mapmaker Explorer Explorer Mapvendor Mapvendor Topographer Mapper Adventurer Pathfinder
  #   Pioneer Mapmonger Wayfinder", "minecraft:fletcher Fletcher Fletcher Bowyer Bowyer Arrowvendor Arrowvendor Arrowman
  #   Bowman Arrowcrafter Bowcrafter Bowvendor Arrowmonger Bowmonger", "minecraft:farmer Farmer Farmer Gardener Gardener
  #   Seedmonger Seedmonger Cropper Greenskeeper Agriculturalist Horticulturist Seedsman Landscaper Seedvendor",
  #   "minecraft:toolsmith Toolsmith Toolsmith Toolmaker Toolmaker Toolvendor Toolvendor Toolworker Toolcrafter Toolman
  #   Toolmaster Tooler Artisan Toolmonger", "minecraft:shepherd Shepherd Shepherd Rancher Rancher Herder Herder Cowhand
  #   Herdsman Cowpuncher Sheepsman Sheeper Cooper Stockman", "minecraft:armorer Armorsmith Armorsmith Armorer Armorer
  #   Armorworker Armorworker Armorvendor Armorvendor Armormaster Armorman Armorcrafter Plateworker Platesmith
  #   Platecrafter Shieldworker Shieldsmith Shieldcrafter Armormonger Platemonger Platevendor Shieldmonger
  #   Shieldvendor", "minecraft:leatherworker Tanner Tanner Leathermaker Leathermaker Leathermonger Leathermonger
  #   Leatherman Skinner Cowskinner Sheepskinner Hidetanner Leathertanner Leathervendor" ]
  villager_names.villager_job_titles = [
    "minecraft:cleric Cleric Cleric Cleric Priest Priest Priest Father Mother Preacher Reverend Rabbi Chaplain Minister Churchman Healer Storyteller Mystic Enchanter Diviner Oracle Augur Prophet Seer Holyman Sage Wiseman Elder",
    "minecraft:butcher Butcher Butcher Meatman Meatman Meatmonger Meatmonger Meatvendor Cowslayer Sheepslayer Chickenslayer Rabbitslayer",
    "minecraft:librarian Librarian Librarian Curator Curator Bookbinder Bookbinder Bookvendor Bookvendor Cataloger Researcher Bookman Bibliothecary Recordkeeper Bookmonger",
    "minecraft:nitwit Nitwit Blockhead Fool Dimwit Dork Dunce Jerk Moron Pinhead Ninny Simpleton Philosopher Daydreamer Roamer Nincompoop",
    "minecraft:fisherman Fisherman Fisherman Fisher Fisher Angler Angler Fishmonger Fishmonger Piscator Rodman Troller Trawler Fishman Skipper Captain Fishvendor",
    "minecraft:weaponsmith Weaponsmith Weaponsmith Swordsmith Swordsmith Weaponmonger Weaponmonger Weaponcrafter Weaponmaker Weaponmaster Weaponman Swordcrafter Swordmaker Swordmaster Weaponvendor Swordmonger Swordvendor",
    "minecraft:cartographer Cartographer Cartographer Mapmaker Mapmaker Explorer Explorer Mapvendor Mapvendor Topographer Mapper Adventurer Pathfinder Pioneer Mapmonger Wayfinder",
    "minecraft:fletcher Fletcher Fletcher Bowyer Bowyer Arrowvendor Arrowvendor Arrowman Bowman Arrowcrafter Bowcrafter Bowvendor Arrowmonger Bowmonger",
    "minecraft:farmer Farmer Farmer Gardener Gardener Seedmonger Seedmonger Cropper Greenskeeper Agriculturalist Horticulturist Seedsman Landscaper Seedvendor",
    "minecraft:toolsmith Toolsmith Toolsmith Toolmaker Toolmaker Toolvendor Toolvendor Toolworker Toolcrafter Toolman Toolmaster Tooler Artisan Toolmonger",
    "minecraft:shepherd Shepherd Shepherd Rancher Rancher Herder Herder Cowhand Herdsman Cowpuncher Sheepsman Sheeper Cooper Stockman",
    "minecraft:armorer Armorsmith Armorsmith Armorer Armorer Armorworker Armorworker Armorvendor Armorvendor Armormaster Armorman Armorcrafter Plateworker Platesmith Platecrafter Shieldworker Shieldsmith Shieldcrafter Armormonger Platemonger Platevendor Shieldmonger Shieldvendor",
    "minecraft:leatherworker Tanner Tanner Leathermaker Leathermaker Leathermonger Leathermonger Leatherman Skinner Cowskinner Sheepskinner Hidetanner Leathertanner Leathervendor"
  ]
