# specialmobs:drowned/_family_of_drowned.toml
# This config contains options that apply to the family of drowned as a whole; that is, the vanilla replacement and
#   all special variants.

  # Environment List fields: General format =
  #     [ "value environment1 condition1 & environment2 condition2 & ...", ... ]
  #   Environment lists are arrays of environment entries. Each entry is a value followed by the environment
  #     conditions that must be satisfied for the value to be chosen. The environments are tested in the order listed,
  #     and the first matching entry is chosen.
  #   See the bottom of this file for an explanation on each environment condition available.



# Category: general
# Options standard to all mob families (that is, not specific to any particular mob family).

  # Whether this mob family replaces vanilla drowned with its vanilla replacement species.
  # The "master_vanilla_replacement" setting in the mod's main config must also be true for this to work.
  # <Boolean> Valid Values: { true, false }, Default: true
  general.vanilla_replacement = true

  # When greater than 0, drowned will have a random render scale applied. This is a visual effect only. If this is set
  #   to a non-negative value, it overrides the value set for "master_random_scaling", though species configs can
  #   override this value.
  # <Number> Range: -1.0 ~ 1.0, Default: -1.0
  general.family_random_scaling = -1.0

  # The chance for drowned to spawn as special variants.
  # NOTE: Some environment check types can cause deadlocks on servers currently, so be careful!
  # <Number> Range: 0.0 ~ 1.0, Default: 0.25
  general.special_variant_chance.base = 0.25
  # The chance for drowned to spawn as special variants when specific environmental conditions are met.
  # <Environment List> Format: [ "value condition1 state1 & condition2 state2 & ...", ... ], Default: [ "0.13
  #   world_time < 120000", "0.5 moon_phase full & special_difficulty >= 0.5", "0.38 moon_phase full", "0.38
  #   special_difficulty >= 0.5" ]
  #    Range for Values: 0.0 ~ 1.0
  general.special_variant_chance.exceptions = [
    "0.13 world_time < 120000",
    "0.5 moon_phase full",
    "0.38 moon_phase full"
  ]

  # The weight of each drowned species to be chosen as the replacement when drowned spawn as special variants. Higher
  #   weight is more common.
  # <Number> Range: ≥ 0.0
  general.weight.abyssal.base = 15.0
  general.weight.brute.base = 60.0
  general.weight.fishing.base = 15.0
  general.weight.frozen.base = 15.0
  general.weight.giant.base = 60.0
  general.weight.hungry.base = 60.0
  general.weight.knight.base = 60.0
  general.weight.plague.base = 60.0
  general.weight.tropical.base = 7.5

  # The weight of each drowned species to be chosen as the replacement when drowned spawn as special variants when
  #   specific environmental conditions are met. Higher weight is more common.
  # <Number> Range: ≥ 0.0
  general.weight.abyssal.exceptions = []
  general.weight.brute.exceptions = []
  general.weight.fishing.exceptions = []
  general.weight.frozen.exceptions = [
    "7.5 dimension_property ultrawarm",
    "300.0 temp freezing",
    "15.0 temp >= 0.8",
    "7.5 temp > 1.0",
    "300.0 biome minecraft:deep_frozen_ocean",
    "150.0 biome minecraft:cold_ocean",
    "150.0 biome minecraft:deep_cold_ocean",
    "15.0 biome minecraft:lukewarm_ocean",
    "15.0 biome minecraft:deep_lukewarm_ocean",
    "7.5 biome minecraft:warm_ocean"
  ]
  general.weight.giant.exceptions = []
  general.weight.hungry.exceptions = []
  general.weight.knight.exceptions = []
  general.weight.plague.exceptions = []
  general.weight.tropical.exceptions = [
    "300.0 biome minecraft:warm_ocean",
    "0.0 temp freezing",
    "0.0 biome minecraft:deep_frozen_ocean"
  ]

  # Environment conditions (for Environment List entries):
  #   Many environment conditions can be inverted by using "!"; these are shown with (!) in the appropriate location.
  #   Other environment conditions are numerical comparisons; these use the operators (shown as op) <, >, =, <=, >=,
  #     or != to compare value.
  # 
  # Valid environment conditions are:
  # 
  #   "dimension_property (!)property":
  #     Valid property values: "ultrawarm", "natural", "has_skylight", "has_ceiling", "fixed_time", "piglin_safe",
  #       "bed_works", "respawn_anchor_works", "has_raids"
  #     Dimension properties are the true/false values available to dimension types in data packs. See the wiki for
  #       more info: [https://minecraft.fandom.com/wiki/Custom_dimension#Syntax].
  # 
  #   "dimension_type (!)namespace:dimension_type_name":
  #     The world's dimension type. In vanilla, these are only "minecraft:overworld", "minecraft:the_nether", or
  #       "minecraft:the_end".
  # 
  #   "rainfall op value":
  #     Biome's rainfall parameter. If this is "= 0", it checks that rain is disabled. For reference, rainfall > 0.85
  #       suppresses fire.
  # 
  #   "biome_temp op value OR (!)freezing":
  #     Biome's temperature parameter. For reference, freezing is < 0.15 and hot is generally considered > 0.95.
  # 
  #   "temp op value OR (!)freezing":
  #     Height-adjusted temperature. For reference, freezing is < 0.15 and hot is generally considered > 0.95.
  # 
  #   "biome_category (!)category":
  #     Deprecated, use "biome_tag" instead!
  # 
  #   "biome_tag (!)#namespace:biome_tag":
  #     The biome tag. See the wiki for vanilla biome tags (resource locations)
  #       [https://minecraft.wiki/w/Biome_tag_(Java_Edition)].
  # 
  #   "biome (!)namespace:biome_name":
  #     The biome. See the wiki for vanilla biome names (resource locations)
  #       [https://minecraft.fandom.com/wiki/Biome#Biome_IDs].
  # 
  #   "structure (!)namespace:structure_name":
  #     The structure. See the wiki for vanilla structure names [https://minecraft.fandom.com/wiki/Structure#ID].
  # 
  #   "y op value":
  #     The y-value. For reference, sea level is normally 63 and lava level is normally -54.
  # 
  #   "y_from_sea op value":
  #     The y-value from sea level. Expect the only air < 0 to be in caves/ravines (which may still have direct view
  #       of the sky).
  # 
  #   "position (!)state":
  #     Valid state values: "can_see_sky", "is_in_village", "is_near_village", "is_near_raid", "is_in_water",
  #       "is_in_lava", "is_in_fluid", "has_redstone_power"
  #     Miscellaneous conditions that generally do what you expect. For reference, 'near' a village is ~3 chunks, and
  #       redstone checks weak power.
  # 
  #   "difficulty op value":
  #     The regional difficulty (0 to 6.75). This is based on many factors such as difficulty setting, moon
  #       brightness, chunk inhabited time, and world time.
  #     For reference, this scales up to the max after 63 days in the world and 150 days in a particular chunk, and
  #       peaks during full moons. On Peaceful this is always 0, on Easy this is 0.75 to 1.5, on Normal this is 1.5 to
  #       4.0, and on Hard this is 2.25 to 6.75.
  # 
  #   "special_difficulty op value":
  #     The 'special multiplier' for regional difficulty (0 to 1). For reference, this is 0 when difficulty <= 2 and 1
  #       when difficulty >= 4.
  #     This is always 0 in Easy and below. In Normal, it maxes at absolute peak regional difficulty. In Hard, it
  #       starts at 0.125 and maxes out in ~50 days.
  # 
  #   "weather (!)type":
  #     Valid type values: "clear", "rain", "thunder"
  # 
  #   "moon_brightness op value":
  #     The moon brightness (0 to 1). New moon has 0 brightness, full moon has 1 brightness. Intermediate phases are
  #       0.25, 0.5, or 0.75.
  # 
  #   "moon_phase (!)phase":
  #     Valid phase values: "full", "waning_gibbous", "last_quarter", "waning_crescent", "new", "waxing_crescent",
  #       "first_quarter", "waxing_gibbous"
  #     For reference, the first day in a new world is always a full moon.
  # 
  #   "day_time (!)time":
  #     Valid time values: "day", "sunset", "night", "sunrise"
  #     Note that the transition periods, sunset & sunrise, are considered as part of day & night, respectively.
  # 
  #   "time_from_midnight op value":
  #     The absolute time in ticks away from midnight. Value must be 0 to 12000.
  # 
  #   "world_time op value":
  #     The total time the world has existed, in ticks. For reference, each day cycle is 24000 ticks and each lunar
  #       cycle is 192000 ticks.
  # 
  #   "chunk_time op value":
  #     The total time the chunk has been loaded, in ticks. For reference, each day cycle is 24000 ticks and each
  #       lunar cycle is 192000 ticks.
  # 
  #   "apocalypse_difficulty op value":
  #     The Apocalypse Rebooted mod's difficulty (scale depends on your config). This is based on the nearest player's
  #       current difficulty level. If no player exists, or the mod is not installed, it will never match any condition.
  # 
  #   "apocalypse_difficulty_or_time op value":
  #     The Apocalypse Rebooted mod's difficulty (scale depends on your config). If the mod is not installed, this is
  #       instead treated like a "world_time" condition.

